version: 2
jobs:
  go-run:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/runzexia/circleci-ghr
    steps:
      - checkout
      - run: go run main.go
  release:
    docker:
      - image: circleci/golang:1.8
    working_directory: /go/src/github.com/runzexia/circleci-ghr
    steps:
      - run: make dist
      - run: make release

workflows:
  version: 2
  run_release:
    jobs:
      - go-run:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - release:
          requires:
            - go-run
          filters:
            branches:
              only: master
            tags:
              only: /.*/
